# Generated by Django 3.0.2 on 2020-11-24 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyPortrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=128)),
                ('mod', models.PositiveIntegerField(default=1)),
                ('remainder', models.PositiveIntegerField(default=0)),
                ('depth', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('contrast', models.BooleanField()),
                ('frame', models.BooleanField(default=True)),
                ('portrait', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFrequencyPortrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_id', models.IntegerField(default=0)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portrait_generator.FrequencyPortrait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
