# Generated by Django 3.0.2 on 2020-11-13 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portrait_generator', '0002_auto_20201113_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyportrait',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='frequencyportrait',
            name='mod',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='frequencyportrait',
            name='remainder',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frequencyportrait',
            name='size',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='UserFrequencyPortrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_id', models.IntegerField(default=0)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portrait_generator.FrequencyPortrait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
