# Generated by Django 3.0.2 on 2020-11-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait_generator', '0003_auto_20201113_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencyportrait',
            name='users',
        ),
    ]
